all:
  hosts:
    192.168.79.136:
      ansible_user: rommel
      ansible_ssh_pass: rommel
      ansible_become_pass: rommel   # Mot de passe sudo
      ansible_python_interpreter: /usr/bin/python3  # Utilisation de Python 3

    

