---
- name: Install and deploy wartest
  hosts: all
  become: yes
  vars:
    image: "{{ image }}"  # Image Docker transmise par Jenkins
    docker_registry_username: "lip33"
    docker_registry_password: "74PNt6dj"

  tasks:
    - name: Ensure Python3 is installed on CentOS
      package:
        name: python3
        state: present

    - name: Install pip on CentOS
      package:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Log in to Docker registry
      docker_login:
        registry: registry.gitlab.com
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"

    - name: Pull the Docker image
      docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run the Docker container
      docker_container:
        name: wartest-container
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
